# Generated by Django 6.0.2 on 2026-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('level', models.CharField(max_length=50)),
                ('total_duration', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('instructor_image', models.ImageField(upload_to='instructor_images/')),
                ('instructor_name', models.CharField(max_length=100)),
                ('instructor_experience', models.CharField(max_length=100)),
            ],
        ),
    ]
