# Generated by Django 6.0.2 on 2026-02-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_featuredcourse_instructor_experience_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.AddField(
            model_name='course',
            name='price1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_image',
            field=models.ImageField(null=True, upload_to='instructor_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featuredCourse',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
