# Generated by Django 6.0.2 on 2026-02-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_level1_course_price1_alter_course_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedCourse',
        ),
    ]
