# Generated by Django 6.0.2 on 2026-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_level_title_alter_price_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
