# Generated by Django 6.0.2 on 2026-03-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_level_name_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.AlterField(
            model_name='level',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
