# Generated by Django 6.0.2 on 2026-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_course_discount_price_course_mark_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_video',
            field=models.FileField(null=True, upload_to='intro_videos/'),
        ),
    ]
