# Generated by Django 6.0.2 on 2026-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_skill_you_will_gain'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_you_will_gain',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
