# Generated by Django 6.0.2 on 2026-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_skill_you_will_gain_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill_you_will_gain',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skill_you_will_gain',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill_you_will_gain',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
