# Generated by Django 6.0.2 on 2026-03-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_skill_you_will_gain_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill_you_will_gain',
            old_name='desc',
            new_name='skill_desc',
        ),
        migrations.RenameField(
            model_name='skill_you_will_gain',
            old_name='skill',
            new_name='skill_name',
        ),
        migrations.AlterField(
            model_name='skill_you_will_gain',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.course'),
        ),
    ]
