# Generated by Django 6.0.2 on 2026-03-02 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_desc_skill_you_will_gain_skill_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.course')),
            ],
        ),
    ]
