# Generated by Django 6.0.2 on 2026-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_requriment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
