# Generated by Django 6.0.2 on 2026-03-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_course_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('curriculum_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='core.curriculumtitle')),
            ],
        ),
    ]
