# Generated by Django 6.0.2 on 2026-03-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_curriculumtitle_curriculumsubtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurriculumSubtitle',
        ),
    ]
