# Generated by Django 6.0.2 on 2026-03-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_section_lesson_delete_curriculumtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
