# Generated by Django 6.0.2 on 2026-03-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_user'),
        ('core', '0025_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
