# Generated by Django 6.0.2 on 2026-03-14 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_name'),
        ('core', '0029_alter_review_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='accounts.userprofile'),
        ),
    ]
