# Generated by Django 6.0.2 on 2026-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_course_level_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
