# Generated by Django 6.0.2 on 2026-03-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
