# Generated by Django 6.0.2 on 2026-03-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='video',
        ),
    ]
