# Generated by Django 6.0.2 on 2026-03-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', null=True, upload_to='course_images/', verbose_name='Course Image'),
        ),
    ]
