# Generated by Django 6.0.2 on 2026-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_course_image_alter_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='wishlist Course Image'),
        ),
    ]
