# Generated by Django 6.0.5 on 2026-08-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='curriculum_videos/'),
        ),
    ]
