# Generated by Django 6.0.5 on 2026-08-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_curriculum_video_delete_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price1',
        ),
    ]
